### ISSUE TITLE
Development Environment Setup

### ISSUE THREAD

**Issue by rasito99** [vottundev/vottun-qubic-bridge-react#1]
Establish a development environment to support frontend development, testing, and debugging.

**Comment by Vicargo** [comment]
- [ ] Create a vite react project with typescript
- [ ] Config eslint and prettier
- [ ] Config playwright for E2E test
- [ ] Config vitest for unit and integration test
- [ ] Integrate TanStack router
- [ ] Integrate TanStack query
- [ ] Config Redux
- [ ] Config shadcn/tailwind
